/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as UeberUnsRouteImport } from './routes/ueber-uns'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as RobotsDottxtRouteImport } from './routes/robots[.]txt'
import { Route as KontaktRouteImport } from './routes/kontakt'
import { Route as ImpressumRouteImport } from './routes/impressum'
import { Route as GalerieRouteImport } from './routes/galerie'
import { Route as DatenschutzRouteImport } from './routes/datenschutz'
import { Route as IndexRouteImport } from './routes/index'
import { Route as LeistungenIndexRouteImport } from './routes/leistungen.index'
import { Route as LeistungenUnfallreparaturRouteImport } from './routes/leistungen.unfallreparatur'
import { Route as LeistungenReifenwechselRouteImport } from './routes/leistungen.reifenwechsel'
import { Route as LeistungenOelwechselRouteImport } from './routes/leistungen.oelwechsel'
import { Route as LeistungenKlimaanlageRouteImport } from './routes/leistungen.klimaanlage'
import { Route as LeistungenHuAuRouteImport } from './routes/leistungen.hu-au'
import { Route as LeistungenBremsenserviceRouteImport } from './routes/leistungen.bremsenservice'
import { Route as LeistungenAchsvermessungRouteImport } from './routes/leistungen.achsvermessung'

const UeberUnsRoute = UeberUnsRouteImport.update({
  id: '/ueber-uns',
  path: '/ueber-uns',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const RobotsDottxtRoute = RobotsDottxtRouteImport.update({
  id: '/robots.txt',
  path: '/robots.txt',
  getParentRoute: () => rootRouteImport,
} as any)
const KontaktRoute = KontaktRouteImport.update({
  id: '/kontakt',
  path: '/kontakt',
  getParentRoute: () => rootRouteImport,
} as any)
const ImpressumRoute = ImpressumRouteImport.update({
  id: '/impressum',
  path: '/impressum',
  getParentRoute: () => rootRouteImport,
} as any)
const GalerieRoute = GalerieRouteImport.update({
  id: '/galerie',
  path: '/galerie',
  getParentRoute: () => rootRouteImport,
} as any)
const DatenschutzRoute = DatenschutzRouteImport.update({
  id: '/datenschutz',
  path: '/datenschutz',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const LeistungenIndexRoute = LeistungenIndexRouteImport.update({
  id: '/leistungen/',
  path: '/leistungen/',
  getParentRoute: () => rootRouteImport,
} as any)
const LeistungenUnfallreparaturRoute =
  LeistungenUnfallreparaturRouteImport.update({
    id: '/leistungen/unfallreparatur',
    path: '/leistungen/unfallreparatur',
    getParentRoute: () => rootRouteImport,
  } as any)
const LeistungenReifenwechselRoute = LeistungenReifenwechselRouteImport.update({
  id: '/leistungen/reifenwechsel',
  path: '/leistungen/reifenwechsel',
  getParentRoute: () => rootRouteImport,
} as any)
const LeistungenOelwechselRoute = LeistungenOelwechselRouteImport.update({
  id: '/leistungen/oelwechsel',
  path: '/leistungen/oelwechsel',
  getParentRoute: () => rootRouteImport,
} as any)
const LeistungenKlimaanlageRoute = LeistungenKlimaanlageRouteImport.update({
  id: '/leistungen/klimaanlage',
  path: '/leistungen/klimaanlage',
  getParentRoute: () => rootRouteImport,
} as any)
const LeistungenHuAuRoute = LeistungenHuAuRouteImport.update({
  id: '/leistungen/hu-au',
  path: '/leistungen/hu-au',
  getParentRoute: () => rootRouteImport,
} as any)
const LeistungenBremsenserviceRoute =
  LeistungenBremsenserviceRouteImport.update({
    id: '/leistungen/bremsenservice',
    path: '/leistungen/bremsenservice',
    getParentRoute: () => rootRouteImport,
  } as any)
const LeistungenAchsvermessungRoute =
  LeistungenAchsvermessungRouteImport.update({
    id: '/leistungen/achsvermessung',
    path: '/leistungen/achsvermessung',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/datenschutz': typeof DatenschutzRoute
  '/galerie': typeof GalerieRoute
  '/impressum': typeof ImpressumRoute
  '/kontakt': typeof KontaktRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/ueber-uns': typeof UeberUnsRoute
  '/leistungen/achsvermessung': typeof LeistungenAchsvermessungRoute
  '/leistungen/bremsenservice': typeof LeistungenBremsenserviceRoute
  '/leistungen/hu-au': typeof LeistungenHuAuRoute
  '/leistungen/klimaanlage': typeof LeistungenKlimaanlageRoute
  '/leistungen/oelwechsel': typeof LeistungenOelwechselRoute
  '/leistungen/reifenwechsel': typeof LeistungenReifenwechselRoute
  '/leistungen/unfallreparatur': typeof LeistungenUnfallreparaturRoute
  '/leistungen/': typeof LeistungenIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/datenschutz': typeof DatenschutzRoute
  '/galerie': typeof GalerieRoute
  '/impressum': typeof ImpressumRoute
  '/kontakt': typeof KontaktRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/ueber-uns': typeof UeberUnsRoute
  '/leistungen/achsvermessung': typeof LeistungenAchsvermessungRoute
  '/leistungen/bremsenservice': typeof LeistungenBremsenserviceRoute
  '/leistungen/hu-au': typeof LeistungenHuAuRoute
  '/leistungen/klimaanlage': typeof LeistungenKlimaanlageRoute
  '/leistungen/oelwechsel': typeof LeistungenOelwechselRoute
  '/leistungen/reifenwechsel': typeof LeistungenReifenwechselRoute
  '/leistungen/unfallreparatur': typeof LeistungenUnfallreparaturRoute
  '/leistungen': typeof LeistungenIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/datenschutz': typeof DatenschutzRoute
  '/galerie': typeof GalerieRoute
  '/impressum': typeof ImpressumRoute
  '/kontakt': typeof KontaktRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/ueber-uns': typeof UeberUnsRoute
  '/leistungen/achsvermessung': typeof LeistungenAchsvermessungRoute
  '/leistungen/bremsenservice': typeof LeistungenBremsenserviceRoute
  '/leistungen/hu-au': typeof LeistungenHuAuRoute
  '/leistungen/klimaanlage': typeof LeistungenKlimaanlageRoute
  '/leistungen/oelwechsel': typeof LeistungenOelwechselRoute
  '/leistungen/reifenwechsel': typeof LeistungenReifenwechselRoute
  '/leistungen/unfallreparatur': typeof LeistungenUnfallreparaturRoute
  '/leistungen/': typeof LeistungenIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/datenschutz'
    | '/galerie'
    | '/impressum'
    | '/kontakt'
    | '/robots.txt'
    | '/sitemap.xml'
    | '/ueber-uns'
    | '/leistungen/achsvermessung'
    | '/leistungen/bremsenservice'
    | '/leistungen/hu-au'
    | '/leistungen/klimaanlage'
    | '/leistungen/oelwechsel'
    | '/leistungen/reifenwechsel'
    | '/leistungen/unfallreparatur'
    | '/leistungen/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/datenschutz'
    | '/galerie'
    | '/impressum'
    | '/kontakt'
    | '/robots.txt'
    | '/sitemap.xml'
    | '/ueber-uns'
    | '/leistungen/achsvermessung'
    | '/leistungen/bremsenservice'
    | '/leistungen/hu-au'
    | '/leistungen/klimaanlage'
    | '/leistungen/oelwechsel'
    | '/leistungen/reifenwechsel'
    | '/leistungen/unfallreparatur'
    | '/leistungen'
  id:
    | '__root__'
    | '/'
    | '/datenschutz'
    | '/galerie'
    | '/impressum'
    | '/kontakt'
    | '/robots.txt'
    | '/sitemap.xml'
    | '/ueber-uns'
    | '/leistungen/achsvermessung'
    | '/leistungen/bremsenservice'
    | '/leistungen/hu-au'
    | '/leistungen/klimaanlage'
    | '/leistungen/oelwechsel'
    | '/leistungen/reifenwechsel'
    | '/leistungen/unfallreparatur'
    | '/leistungen/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DatenschutzRoute: typeof DatenschutzRoute
  GalerieRoute: typeof GalerieRoute
  ImpressumRoute: typeof ImpressumRoute
  KontaktRoute: typeof KontaktRoute
  RobotsDottxtRoute: typeof RobotsDottxtRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  UeberUnsRoute: typeof UeberUnsRoute
  LeistungenAchsvermessungRoute: typeof LeistungenAchsvermessungRoute
  LeistungenBremsenserviceRoute: typeof LeistungenBremsenserviceRoute
  LeistungenHuAuRoute: typeof LeistungenHuAuRoute
  LeistungenKlimaanlageRoute: typeof LeistungenKlimaanlageRoute
  LeistungenOelwechselRoute: typeof LeistungenOelwechselRoute
  LeistungenReifenwechselRoute: typeof LeistungenReifenwechselRoute
  LeistungenUnfallreparaturRoute: typeof LeistungenUnfallreparaturRoute
  LeistungenIndexRoute: typeof LeistungenIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/ueber-uns': {
      id: '/ueber-uns'
      path: '/ueber-uns'
      fullPath: '/ueber-uns'
      preLoaderRoute: typeof UeberUnsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/robots.txt': {
      id: '/robots.txt'
      path: '/robots.txt'
      fullPath: '/robots.txt'
      preLoaderRoute: typeof RobotsDottxtRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/kontakt': {
      id: '/kontakt'
      path: '/kontakt'
      fullPath: '/kontakt'
      preLoaderRoute: typeof KontaktRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/impressum': {
      id: '/impressum'
      path: '/impressum'
      fullPath: '/impressum'
      preLoaderRoute: typeof ImpressumRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/galerie': {
      id: '/galerie'
      path: '/galerie'
      fullPath: '/galerie'
      preLoaderRoute: typeof GalerieRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/datenschutz': {
      id: '/datenschutz'
      path: '/datenschutz'
      fullPath: '/datenschutz'
      preLoaderRoute: typeof DatenschutzRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/leistungen/': {
      id: '/leistungen/'
      path: '/leistungen'
      fullPath: '/leistungen/'
      preLoaderRoute: typeof LeistungenIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/leistungen/unfallreparatur': {
      id: '/leistungen/unfallreparatur'
      path: '/leistungen/unfallreparatur'
      fullPath: '/leistungen/unfallreparatur'
      preLoaderRoute: typeof LeistungenUnfallreparaturRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/leistungen/reifenwechsel': {
      id: '/leistungen/reifenwechsel'
      path: '/leistungen/reifenwechsel'
      fullPath: '/leistungen/reifenwechsel'
      preLoaderRoute: typeof LeistungenReifenwechselRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/leistungen/oelwechsel': {
      id: '/leistungen/oelwechsel'
      path: '/leistungen/oelwechsel'
      fullPath: '/leistungen/oelwechsel'
      preLoaderRoute: typeof LeistungenOelwechselRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/leistungen/klimaanlage': {
      id: '/leistungen/klimaanlage'
      path: '/leistungen/klimaanlage'
      fullPath: '/leistungen/klimaanlage'
      preLoaderRoute: typeof LeistungenKlimaanlageRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/leistungen/hu-au': {
      id: '/leistungen/hu-au'
      path: '/leistungen/hu-au'
      fullPath: '/leistungen/hu-au'
      preLoaderRoute: typeof LeistungenHuAuRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/leistungen/bremsenservice': {
      id: '/leistungen/bremsenservice'
      path: '/leistungen/bremsenservice'
      fullPath: '/leistungen/bremsenservice'
      preLoaderRoute: typeof LeistungenBremsenserviceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/leistungen/achsvermessung': {
      id: '/leistungen/achsvermessung'
      path: '/leistungen/achsvermessung'
      fullPath: '/leistungen/achsvermessung'
      preLoaderRoute: typeof LeistungenAchsvermessungRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DatenschutzRoute: DatenschutzRoute,
  GalerieRoute: GalerieRoute,
  ImpressumRoute: ImpressumRoute,
  KontaktRoute: KontaktRoute,
  RobotsDottxtRoute: RobotsDottxtRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  UeberUnsRoute: UeberUnsRoute,
  LeistungenAchsvermessungRoute: LeistungenAchsvermessungRoute,
  LeistungenBremsenserviceRoute: LeistungenBremsenserviceRoute,
  LeistungenHuAuRoute: LeistungenHuAuRoute,
  LeistungenKlimaanlageRoute: LeistungenKlimaanlageRoute,
  LeistungenOelwechselRoute: LeistungenOelwechselRoute,
  LeistungenReifenwechselRoute: LeistungenReifenwechselRoute,
  LeistungenUnfallreparaturRoute: LeistungenUnfallreparaturRoute,
  LeistungenIndexRoute: LeistungenIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
